CREATE DATABASE auth;
CREATE DATABASE bugs;
CREATE DATABASE profiles;

GRANT ALL PRIVILEGES ON DATABASE auth TO admin;
GRANT ALL PRIVILEGES ON DATABASE bugs TO admin;
GRANT ALL PRIVILEGES ON DATABASE profiles TO admin;
